### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/kube-cluster#2]
- [ ] Rewrite with Ansible

- [ ] Add K8S permanent volume

- [ ] Make proper Jenkins deployment
